### PR TITLE
Add new options for scaling

### PR DESCRIPTION
**Pull request by bobbyhubbard**
I added a few new options for scaling that are less dependent on a duration in order to scale safely.

- Add support for instance batches (--batch-size) instead of scaling 1 at a time
- Add support for ensuring the new instances are actually started before scaling down the old instance (--wait-for-start)
- Add ability to wait for a configurable time AFTER the start for apps that take long to bootstrap (--post-start-sleep)

For purposes of the merge, I also removed the vendored packages. No new api's were utilized.

### CODE REVIEW

**Comment by bobbyhubbard** [comment]
Is this project still active?

**Comment by bobbyhubbard** [comment]
Following up on this pull. Too scary? :)

**Comment by krujos** [comment]
sorry @bobbyhubbard more inattentiveness! Will get to it this week!

**Comment by bobbyhubbard** [comment]
We've been using this branch here at Garmin for about a month now for prod pipelines and so far its been great. There are a few recommended enhancements (% of running instances vs a specific # of instances, better doc and option validation, etc) from users that I'd like to get included eventually. If you dont think this is gonna get merged and belongs in a different project, please let me know and I'll go that direction.

**Comment by bobbyhubbard** [comment]
So is this project dead? If I fix the merge conflict can you review it for inclusion?

**Pull request merged**
